[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat username=:username"
  status = 200
  query = {username = ":username"}